package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-04-12T22:25:28.135+08:00
 * Generated source version: 3.5.2
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "WeatherSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WeatherSoap {

    @WebMethod(operationName = "GetSST", action = "http://tempuri.org/GetSST")
    @RequestWrapper(localName = "GetSST", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSST")
    @ResponseWrapper(localName = "GetSSTResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSSTResponse")
    @WebResult(name = "GetSSTResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getSST(

        @WebParam(name = "_location", targetNamespace = "http://tempuri.org/")
        java.lang.String location
    );

    @WebMethod(operationName = "GetGamePrediction", action = "http://tempuri.org/GetGamePrediction")
    @RequestWrapper(localName = "GetGamePrediction", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetGamePrediction")
    @ResponseWrapper(localName = "GetGamePredictionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetGamePredictionResponse")
    @WebResult(name = "GetGamePredictionResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getGamePrediction(

        @WebParam(name = "sLocation", targetNamespace = "http://tempuri.org/")
        java.lang.String sLocation
    );

    @WebMethod(operationName = "GetLures", action = "http://tempuri.org/GetLures")
    @RequestWrapper(localName = "GetLures", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLures")
    @ResponseWrapper(localName = "GetLuresResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLuresResponse")
    @WebResult(name = "GetLuresResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getLures(

        @WebParam(name = "BodyOfWater", targetNamespace = "http://tempuri.org/")
        java.lang.String bodyOfWater,
        @WebParam(name = "PredictTime", targetNamespace = "http://tempuri.org/")
        java.lang.String predictTime,
        @WebParam(name = "Weather", targetNamespace = "http://tempuri.org/")
        java.lang.String weather,
        @WebParam(name = "WaterTemp", targetNamespace = "http://tempuri.org/")
        java.lang.String waterTemp,
        @WebParam(name = "WaterColor", targetNamespace = "http://tempuri.org/")
        java.lang.String waterColor
    );

    @WebMethod(operationName = "GetWeather", action = "http://tempuri.org/GetWeather")
    @RequestWrapper(localName = "GetWeather", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWeather")
    @ResponseWrapper(localName = "GetWeatherResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWeatherResponse")
    @WebResult(name = "GetWeatherResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getWeather(

        @WebParam(name = "sLocation", targetNamespace = "http://tempuri.org/")
        java.lang.String sLocation,
        @WebParam(name = "sLat", targetNamespace = "http://tempuri.org/")
        java.lang.String sLat,
        @WebParam(name = "sLong", targetNamespace = "http://tempuri.org/")
        java.lang.String sLong
    );

    @WebMethod(operationName = "GetCurrentWeatherConditions", action = "http://tempuri.org/GetCurrentWeatherConditions")
    @RequestWrapper(localName = "GetCurrentWeatherConditions", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCurrentWeatherConditions")
    @ResponseWrapper(localName = "GetCurrentWeatherConditionsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCurrentWeatherConditionsResponse")
    @WebResult(name = "GetCurrentWeatherConditionsResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getCurrentWeatherConditions(

        @WebParam(name = "sLocation", targetNamespace = "http://tempuri.org/")
        java.lang.String sLocation,
        @WebParam(name = "sLat", targetNamespace = "http://tempuri.org/")
        java.lang.String sLat,
        @WebParam(name = "sLong", targetNamespace = "http://tempuri.org/")
        java.lang.String sLong
    );

    @WebMethod(operationName = "GetMarineWeather", action = "http://tempuri.org/GetMarineWeather")
    @RequestWrapper(localName = "GetMarineWeather", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMarineWeather")
    @ResponseWrapper(localName = "GetMarineWeatherResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMarineWeatherResponse")
    @WebResult(name = "GetMarineWeatherResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getMarineWeather(

        @WebParam(name = "_location", targetNamespace = "http://tempuri.org/")
        java.lang.String location
    );

    @WebMethod(operationName = "GetMoonPhase", action = "http://tempuri.org/GetMoonPhase")
    @RequestWrapper(localName = "GetMoonPhase", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMoonPhase")
    @ResponseWrapper(localName = "GetMoonPhaseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMoonPhaseResponse")
    @WebResult(name = "GetMoonPhaseResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getMoonPhase(

        @WebParam(name = "year", targetNamespace = "http://tempuri.org/")
        int year,
        @WebParam(name = "month", targetNamespace = "http://tempuri.org/")
        int month,
        @WebParam(name = "day", targetNamespace = "http://tempuri.org/")
        int day
    );

    @WebMethod(operationName = "GetCurrentWeatherConditionsImageTemp", action = "http://tempuri.org/GetCurrentWeatherConditionsImageTemp")
    @RequestWrapper(localName = "GetCurrentWeatherConditionsImageTemp", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCurrentWeatherConditionsImageTemp")
    @ResponseWrapper(localName = "GetCurrentWeatherConditionsImageTempResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCurrentWeatherConditionsImageTempResponse")
    @WebResult(name = "GetCurrentWeatherConditionsImageTempResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getCurrentWeatherConditionsImageTemp(

        @WebParam(name = "sLocation", targetNamespace = "http://tempuri.org/")
        java.lang.String sLocation,
        @WebParam(name = "sLat", targetNamespace = "http://tempuri.org/")
        java.lang.String sLat,
        @WebParam(name = "sLong", targetNamespace = "http://tempuri.org/")
        java.lang.String sLong
    );

    @WebMethod(operationName = "GetTides", action = "http://tempuri.org/GetTides")
    @RequestWrapper(localName = "GetTides", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTides")
    @ResponseWrapper(localName = "GetTidesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTidesResponse")
    @WebResult(name = "GetTidesResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getTides(

        @WebParam(name = "_location", targetNamespace = "http://tempuri.org/")
        java.lang.String location
    );

    @WebMethod(operationName = "GetSSTCharts", action = "http://tempuri.org/GetSSTCharts")
    @RequestWrapper(localName = "GetSSTCharts", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSSTCharts")
    @ResponseWrapper(localName = "GetSSTChartsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSSTChartsResponse")
    @WebResult(name = "GetSSTChartsResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getSSTCharts(

        @WebParam(name = "_location", targetNamespace = "http://tempuri.org/")
        java.lang.String location
    );
}
